<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-15T17:58:44 IST" name="Suite" finished-at="2023-12-15T17:59:28 IST" duration-ms="43790">
    <groups>
    </groups>
    <test started-at="2023-12-15T17:58:44 IST" name="Test1" finished-at="2023-12-15T17:59:04 IST" duration-ms="20541">
      <class name="TestngScreenshot.NewTest">
        <test-method signature="LogInOrangeHRM()[pri:0, instance:TestngScreenshot.NewTest@75d4a5c2]" started-at="2023-12-15T17:58:44 IST" name="LogInOrangeHRM" finished-at="2023-12-15T17:59:04 IST" duration-ms="20340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogInOrangeHRM -->
      </class> <!-- TestngScreenshot.NewTest -->
    </test> <!-- Test1 -->
    <test started-at="2023-12-15T17:59:05 IST" name="Test2" finished-at="2023-12-15T17:59:18 IST" duration-ms="12859">
      <class name="TestngScreenshot.NewTest">
        <test-method signature="LoginFacebook()[pri:0, instance:TestngScreenshot.NewTest@65e98b1c]" started-at="2023-12-15T17:59:05 IST" name="LoginFacebook" finished-at="2023-12-15T17:59:18 IST" duration-ms="12848" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFacebook -->
      </class> <!-- TestngScreenshot.NewTest -->
    </test> <!-- Test2 -->
    <test started-at="2023-12-15T17:59:18 IST" name="Test3" finished-at="2023-12-15T17:59:28 IST" duration-ms="10168">
      <class name="TestngScreenshot.NewTest">
        <test-method signature="LoginVtiger()[pri:0, instance:TestngScreenshot.NewTest@6ad82709]" started-at="2023-12-15T17:59:18 IST" name="LoginVtiger" finished-at="2023-12-15T17:59:28 IST" duration-ms="10142" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Dashboard] but found [vtiger]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Dashboard] but found [vtiger]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestngScreenshot.NewTest.LoginVtiger(NewTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginVtiger -->
      </class> <!-- TestngScreenshot.NewTest -->
    </test> <!-- Test3 -->
  </suite> <!-- Suite -->
</testng-results>
